name: LinkedIn Job Posting

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 09:00 UTC

jobs:
  post_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          AUTHORIZATION_CODE: ${{ secrets.AUTHORIZATION_CODE }}
          LINKEDIN_GROUP_ID: ${{ secrets.LINKEDIN_GROUP_ID }}
        run: |
          python linkedin_oauth.py
